### ISSUE TITLE
Feature: Typescript definitions

### ISSUE THREAD

**Issue by KilianSSL** [bucharest-gold/opossum#213]
I'd love to use this library in a typescript project. However the definitions are not yet there.
Would it be possible to put this on the roadmap?

**Comment by lance** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

**Comment by quinnlangille** [comment]
I see this was opened a while ago. Has anyone started on it? If not I can make the PR, just lemme know!

**Comment by KilianSSL** [comment]
Haven't started. Feel free to PR.

**Comment by quinnlangille** [comment]
I've submitted types to DefinitelyTyped here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29637

**Comment by quinnlangille** [comment]
PR's been merged, feel free to install `@types/opossum` and lemme know if you see any issues!

**Comment by lance** [comment]
@quinnlangille thanks for contributing this! This issue has been in the back of my mind for a long time, but has never percolated to the top. TBQH, I don't use TypeScript much so I kept avoid it. As it turns out, it seems the implementation was pretty straightforward. 

I'm going to close this issue now. Thanks again!
