### ISSUE TITLE
Feature request: minimum request volume

### ISSUE THREAD

**Issue by arkwright** [bucharest-gold/opossum#232]
Hey, thanks for writing such an awesome library!

It would be really helpful if opossum could support a minimum request volume within the rolling window, below which the circuit would never open, even if 100% of requests result in errors. I am currently experiencing an issue wherein traffic occasionally drops to a trickle, and then the circuit opens because the first error after a long, silent period tips the statistics beyond the `errorThresholdPercentage`. I could increase the `rollingCountTimeout`, though this would effectively decrease the circuit breaker's sensitivity when traffic volume is sufficient.

**Comment by lance** [comment]
Hi @arkwright thanks for the suggestion and nice words. :) This is very similar to the `options.warmUp` property that was recently added. But I can see that it is different in that the warm up phase only happens when the application starts up. Your suggestion seems to encompass both a warm up phase, and an idle phase, so I need to give it some thought. I believe it should be possible to have a single property that handles both cases. I'd rather not have two separate code paths doing essentially the same thing. 

Brainstorming a hack/workaround until I figure this out... Could your fallback function check `stats.fires` to see if it meets your threshold, and if it does not then call `circuit.close()`?

**Comment by arkwright** [comment]
Hey @lance, thanks for giving this some thought!

I recently considered writing a fallback function which looks at `stats.fires`, and that would provide the functionality I'm looking for. I just felt that this would be such a common use case that it would make sense to expose it as a configuration option. `circuit-breaker-js` provides a [`volumeThreshold`](https://github.com/yammer/circuit-breaker-js#volumethreshold) option, for example.

I'm not sure if `warmUp` could handle both cases, but I think the inverse API might work. If `warmUp` was deprecated and replaced with a `volumeThreshold`:

1. At application start up, the circuit would remain closed until at least `volumeThreshold` requests have been sent, providing behavior similar to `warmUp`.
2. During idle periods, the circuit would remain closed until `volumeThreshold` requests occur within the rolling window, providing the desired low volume protection.

Of course, if backward compatibility is a concern, these two options could coexist safely.

I'm not sure if that helps, but that's how I might approach it!
